language: node_js
node_js:
  - '10'
install:
  - npm ci --prefix web
  - npm ci --prefix functions
script:
  - npm run build.prod --prefix web
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
