language: node_js
node_js:
  - '12'
install:
  - npm ci --prefix web
  - npm ci --prefix functions
script:
  - npm run lint --prefix web
  - npm run lint --prefix functions
  - npm run prebuild --prefix web
  - npm run build.prod --prefix web
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  message: $TRAVIS_COMMIT
notifications:
  slack: $SLACK_NOTIFICATION
