language: node_js
node_js:
  - '10'
install: 
  - npm install -g firebase-tools
script:
  - cd web
  - npm install
  - npm run build.prod
  - cd ..
  - cd functions
  - npm install
after_success:
  - firebase deploy --token $FIREBASE_TOKEN