language: node_js
node_js:
  - '10'
install:
  - npm install -g firebase-tools
  - npm install --prefix web
  - npm install --prefix functions
script:
  - npm run build.prod --prefix web
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
