language: node_js
node_js:
  - '10'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install: 
  - npm install -g firebase-tools
script:
  - cd web
  - npm install
  - npm run build.prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN